name: Build & Push Images
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (optional for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & tag
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/web
          TAG_SHA=sha-${GITHUB_SHA::7}  
          
          docker build -t $IMAGE:${TAG_SHA} -t $IMAGE:latest .
          
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            PR=${GITHUB_REF#refs/pull/}   # extract PR number from ref
            docker tag $IMAGE:${TAG_SHA} $IMAGE:pr-$PR
            docker push $IMAGE:pr-$PR
          fi
          
          docker push $IMAGE:${TAG_SHA}
          docker push $IMAGE:latest
