name: Cleanup PR Preview
on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Remove preview containers + nginx config
      - name: Remove preview container + nginx
        run: |
          set -euo pipefail
          chmod +x ./scripts/remove_preview.sh
          PR_NUMBER=${{ github.event.pull_request.number }}
          ./scripts/remove_preview.sh $PR_NUMBER

      # 3️⃣ Delete PR image from GHCR
      - name: Delete GHCR image tag for PR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          owner: ${{ github.repository_owner }}
          package_name: web
          tag: pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          