name: Cleanup PR preview
on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Remove preview container + nginx
        run: |
          chmod +x ./scripts/remove_preview.sh
          PR=${{ github.event.pull_request.number }}
          ./scripts/remove_preview.sh $PR

      - name: Delete GHCR image tag for PR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          owner: ${{ github.repository_owner }}
          package_name: web
          tag: pr-${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
