name: Cleanup PR Previews

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to cleanup'
        required: true
        type: string

jobs:
  cleanup-preview:
    runs-on: self-hosted
    if: github.event.action == 'closed' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Remove PR preview
        run: |
          export GITHUB_REPOSITORY="${{ github.repository }}"
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./scripts/remove-preview.sh ${{ steps.pr.outputs.number }}

      - name: Delete container registry tag
        continue-on-error: true
        run: |
          # Get package versions
          PACKAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/web
          
          # Delete the PR tag
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/user/packages/container/${PACKAGE_NAME}/versions" \
            -d '{"tagged":"pr-${{ steps.pr.outputs.number }}"}' \
            || echo "Could not delete registry tag (might not exist)"

      - name: Comment PR cleanup
        if: github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🧹 PR Preview Cleaned Up
            
            The preview environment for this PR has been removed:
            - Container stopped and removed
            - Registry tag deleted
            - Resources cleaned up
            
            **Cleanup completed at:** ${new Date().toISOString()}`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr.outputs.number }},
              body: comment
            });